CREATE TABLE IF NOT EXISTS waitlist_signups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  business VARCHAR(160) NOT NULL,
  city VARCHAR(120) NOT NULL,
  whatsapp VARCHAR(32) NOT NULL,
  email VARCHAR(190) NOT NULL,
  ip VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY waitlist_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
